title: snowbird91
description: >
  Andrew (snowbird91) | tjcsc & 0xf1sh | forensics, crypto, OSINT write-ups.
url: https://ctf.snowbird91.xyz
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM

author:
  name: "snowbird91 (Andrew)"
  email: ""

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: "write-ups"
    values:
      layout: "post"
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
